atinc/ngx-tethys

- src/datepicker/datepicker.directive.ts
- src/datepicker/daterangepicker.directive.ts
- src/datepicker/styles/datepicker.scss
> daterangepicker and datepicker  add cacalculatePosition

- src/directive/thy-enter.directive.ts
> fix(thy-enter): 去除thy-enter触发事件preventDefault的调用，交给用户处理

- demo/src/app/components/+select/select-section.component.html
- demo/src/app/components/+select/select-section.component.ts
- src/select/select-container.component.html
- src/select/select-container.component.ts
- src/select/select-custom.spec.ts
应该要销毁clear searchText,
增加部分测试、示例demo
> fix(select-custom): custom-select 组件打开后搜索在关闭，showOptions

- demo/src/app/components/+dialog/dialog-content.component.html
- demo/src/app/components/+dialog/dialog-section.component.html
- demo/src/app/components/+dialog/dialog-section.component.ts
- src/dialog/dialog-ref.ts
- src/dialog/dialog.config.ts
- src/dialog/dialog.service.ts
- src/dialog/styles/dialog.scss
- src/dialog/test/dialog.spec.ts
- src/dialog/test/module.ts
- src/styles/variables.scss
> feat(dialog): add size supper-lg and perfect dialog test cases

- demo/src/app/components/+pop-box/pop-box-section.component.ts
- package-lock.json
- src/pop-box/styles/pop-box.scss
fix pop box template when have mask click header or click footer then pop box hide and did not execute bind footer event
> fix(pop-box):  fix pop box click footer or header hided, when thyMask is true

- demo/src/app/components/+tree-select/mock-data.ts
- demo/src/app/components/+tree-select/tree-select-section.component.html
- demo/src/app/components/+tree-select/tree-select-section.component.ts
- src/select/styles/select.scss
- src/tree-select/tree-select-nodes.component.html
- src/tree-select/tree-select.component.html
- src/tree-select/tree-select.component.ts
- src/tree-select/tree-select.spec.ts
> thy-tree-select

- demo/src/styles.scss
- package-lock.json
- package.json
更新编辑器样式引入方式
@import '~@ngx-tethys/editor/src/lib/styles/editor.scss';
> feat(editor): update editor and the way of editor style introduction

- demo/src/app/components/+layout/layout-section.component.html
- demo/src/app/components/+reboot/reboot-section.component.html
- demo/src/app/components/+select/select-section.component.html
- src/form/form-group.component.html
- src/grid/grid.component.html
- src/select/option-group.component.html
- src/styles/modules/util.scss
- src/styles/variables.scss
- src/tree-select/tree-select-nodes.component.html
need to replace test-info to text-desc, test-info will be new color in the future
> feat(color): change success color and add text-desc replace text-info

- src/store/action.ts
- src/store/spec/store.spec.ts
let default parameters available  in Action
> fix(store): remove latest snapshot args for Action #238030

- src/pagination/pagination.component.html
- src/pagination/pagination.component.ts
- src/pagination/styles/mixin.scss
- src/pagination/styles/pagination.scss
- src/pagination/styles/theme.scss
> fix(pagination): change class name

- demo/src/app/app.component.html
- demo/src/app/components/+list/list-section.component.html
- demo/src/app/components/+list/list-section.component.ts
- src/core/option/list-option.component.html
- src/core/option/list-option.component.ts
- src/core/option/option.mixin.scss
- src/list/selection/selection-list.spec.ts
- src/list/selection/selection-list.ts
- src/list/styles/list.scss
- src/list/styles/theme.scss
> feat(selection-list): thyLayout support 'list'

- demo/src/app/components/+property-operation/api-parameters.ts
- demo/src/app/components/+property-operation/basic/basic.component.html
- demo/src/app/components/+property-operation/property-operation-section.component.html
- demo/src/app/components/+property-operation/property-operation-section.component.ts
- src/button/button-icon.spec.ts
- src/core/testing/index.ts
- src/core/testing/thy-icon.ts
- src/icon/test/icon.spec.ts
- src/property-operation/module.ts
- src/property-operation/property-operation.component.html
- src/property-operation/property-operation.component.ts
- src/property-operation/styles/property-operation.scss
- src/property-operation/test/property-operation.component.spec.ts
- src/select/custom-select.spec.ts
refactor property-operation test for thy-icon, add test utils to core/testing/thy-icon
> feat(property-operation): support thy-icon #243057

- src/styles/variables.scss
- src/transfer/styles/transfer.scss
- src/transfer/transfer.component.html
> style(transfer): #252474 fix item and middle icon

- demo/src/app/components/+action-menu/action-menu-section.component.html
- demo/src/app/components/+reboot/reboot-section.component.html
- src/action-menu/styles/action-menu.scss
- src/styles/variables.scss
> feat(action menu): ui

- src/nav/styles/mixin.scss
thy-nav下加button按钮，button的thy-icon颜色失效
> fix(agile): #255003 thy-nav下加button按钮，button的thy-icon颜色失效

- src/styles/variables.scss
thy-dialog-footer 原 上下间距 10px
修改为 15px
> 【dialog】页脚 padding 修改

- demo/src/app/components/+dialog/api-parameters.ts
- demo/src/app/components/+dialog/dialog-content.component.html
- demo/src/app/components/+dialog/dialog-section.component.html
- demo/src/app/components/+dialog/dialog-section.component.ts
- src/core/testing/thy-icon.ts
- src/dialog/dialog.module.ts
- src/dialog/header/dialog-header.component.html
- src/dialog/header/dialog-header.component.ts
- src/dialog/styles/dialog.scss
- src/dialog/test/dialog-layout.spec.ts
- src/dialog/test/dialog.spec.ts
- src/styles/variables.scss
if you don't need pill close style please set $dialog-close-pill-enabled as false
> feat(dialog): add thySize for header, add pill style for close #264303

- src/core/option/list-option.component.ts
when list is not multiple and item is selected
> fix(list): not call toggleOption() #265188

- demo/src/app/components/+action-menu/action-menu-section.component.html
- src/action-menu/styles/action-menu.scss
> style(action-menu): padding from 5 to 10px #265183

- demo/src/app/components/+slide/slide-content.component.html
- demo/src/app/components/+slide/slide-content.component.ts
- src/popover/popover-container.component.ts
- src/slide/slide-animations.ts
- src/slide/slide-container.component.ts
- src/slide/slide.config.ts
- src/slide/slide.service.ts
- src/slide/styles/slide.scss
- src/util/helpers.ts
add animation when slide has offset
> feat(slide): add .active to trigger,add animation

- demo/src/app/components/+action-menu/action-menu-section.component.html
- demo/src/app/components/+popover/basic/popover-basic.component.html
- demo/src/app/components/+popover/basic/popover-basic.component.ts
- src/action-menu/action-menu-toggle.component.ts
- src/action-menu/action-menu.module.ts
> refactor(action-menu): replace pbox with popover

- src/styles/variables.scss
- src/switch/styles/switch.scss
> feat(switch): add $switch-margin-bottom to switch

- demo/src/app/global/+link/basic/link-basic.component.html
- src/styles/modules/link.scss
- src/styles/modules/link.theme.scss
> feat: ##266961 ngx-tethys】添加link-muted,颜色为#888

- demo/src/app/components/+breadcrumb/breadcrumb-section.component.html
- src/breadcrumb/styles/breadcrumb.scss
- src/breadcrumb/styles/theme.scss
- src/styles/variables.scss
icon color #aaa
text color #888
> feat(breadcrumb): chang icon and text color #267177

- src/badge/styles/badge.scss
- src/core/option/option.mixin.scss
- src/list/styles/list.scss
- src/list/styles/theme.scss
> style(list): modify list hover bg to fafafa

- src/core/option/option.mixin.scss
- src/select/custom-select/styles/custom-select-option.scss
> fix(select): fix option paddingRight from 35 to 20

- src/core/option/list-option.component.html
- src/core/option/module.ts
- src/core/option/option.mixin.scss
> fix(list): replace icon

- src/date-picker/lib/calendar/calendar-footer.component.html
- src/date-picker/lib/lib-packer.module.ts
- src/date-picker/picker.component.html
- src/date-picker/picker.validators.ts
- src/date-picker/style/picker.scss
- src/date-picker/style/time-picker.scss
- src/module.ts
- src/public-api.ts
- src/styles/index.scss
- src/time-picker/index.ts
- src/time-picker/style.scss
- src/time-picker/time-picker-controls.util.ts
- src/time-picker/time-picker.component.html
- src/time-picker/time-picker.component.ts
- src/time-picker/time-picker.config.ts
- src/time-picker/time-picker.models.ts
- src/time-picker/time-picker.module.ts
- src/time-picker/time-picker.store.ts
- src/time-picker/time-picker.utils.ts
remove the ngx-bootstrap dependence of date-picker
> feat(time-picker): add thyTimePickerModule #INF-332

- demo/src/app/app.module.ts
- demo/src/app/components/+dialog/basic/dialog-basic.component.html
- demo/src/app/components/+dialog/basic/dialog-basic.component.ts
- demo/src/app/components/+dialog/dialog-content.component.html
- demo/src/app/components/+dialog/dialog-content.component.ts
- src/dialog/dialog.config.ts
- src/dialog/dialog.module.ts
- src/dialog/footer/dialog-footer.component.html
- src/dialog/footer/dialog-footer.component.ts
- src/dialog/styles/dialog.scss
- src/dialog/test/dialog-layout.spec.ts
add config dialogLayout in golbal and com; add desc template
> feat(dialog-footer): add actionsAlign

- demo/src/app/components/+datepicker/datepicker-section.component.ts
- demo/src/app/components/+datepicker/default-picker-value/datepicker-default-picker-value.component.html
- demo/src/app/components/+datepicker/default-picker-value/datepicker-default-picker-value.component.ts
- demo/src/app/components/+datepicker/disabled-date/datepicker-disabled-date.component.html
- demo/src/app/components/+datepicker/disabled-date/datepicker-disabled-date.component.ts
- demo/src/app/components/+datepicker/index.ts
- src/date-picker/abstract-picker.component.ts
- src/date-picker/base-picker.component.html
- src/date-picker/base-picker.component.ts
- src/date-picker/date-picker.component.spec.ts
- src/date-picker/lib/popups/date-popup.component.ts
- src/date-picker/picker.util.ts
> feat(date-picker): support default picker value

- src/date-picker/abstract-picker.directive.ts
- src/date-picker/date-picker.directive.spec.ts
thyDefaultPickerValue, thyMinDate, thyMaxDate
> fix(date-picker): repair directive does not pass parameters

- demo/src/app/components/+datepicker/directive/datepicker-directive.component.html
- demo/src/app/components/+datepicker/disabled-date/datepicker-disabled-date.component.ts
- demo/src/app/components/+datepicker/time/datepicker-time.component.html
- demo/src/app/components/+datepicker/time/datepicker-time.component.ts
- src/date-picker/abstract-picker.component.ts
- src/date-picker/abstract-picker.directive.ts
- src/date-picker/base-picker.component.ts
- src/date-picker/date-picker.component.spec.ts
- src/date-picker/date-picker.directive.spec.ts
- src/date-picker/date-picker.module.ts
- src/date-picker/lib/calendar/calendar-footer.component.html
- src/date-picker/lib/popups/date-popup.component.ts
- src/date-picker/picker.pipes.ts
- src/date-picker/picker.util.ts
according to with_time correspond format string
fix directive date picker with_time logic
> fix(date-picker): add format string pipe and fix minDate logic

- .prettierrc.js
- src/button/styles/button-icon.scss
- src/button/styles/mixin.scss
- src/styles/modules/editable.scss
- src/styles/variables.scss
…e way for font family #INFR-395
> refactor(styles): refactor input and button styles variables, pave the way for font family #INFR-395

- src/styles/modules/icon-text.scss
- src/styles/variables.scss
the new font-family causes button not to center vertically, should change line-height from 1.5 to 1.47 and update padding-y fit right size
> feat(styles): change global font-family and set input-btn line-height as 1.47 for center vertically #INFR-395

- src/transfer/transfer-list.component.html
- src/transfer/transfer.module.ts
> fix(transfer): change cursor when dragging

- src/nav/styles/theme.scss
- src/styles/variables.scss
> fix(nav): 修复thirdly 三级导航换肤后样式问题(#INFR-849)

- src/dialog/styles/dialog.scss
- src/styles/variables.scss
dialog footer words position when align set
> fix(dialog): dialog footer words position when align set #INFR-860

- src/pagination/pagination.component.spec.ts
words and active when pageIndex set
> test(pagination): words and active when pageIndex set #INFR-811

- src/tree/styles/tree.scss
- src/tree/test/mock.ts
- src/tree/test/tree.spec.ts
- src/tree/tree-node.component.html
- src/tree/tree-node.component.ts
- src/tree/tree.component.html
hide drag icon when tree with thyBeforeDragStart
> fix(tree): hide drag icon when tree with thyBeforeDragStart #INFR-489

- commitlint.config.js
- schematics/ng-add/index.spec.ts
- schematics/ng-add/index.ts
- schematics/testing/index.ts
- schematics/testing/test-app.ts
- schematics/testing/test-lib.ts
- schematics/testing/test-project.ts
- schematics/utils/get-project.ts
- schematics/utils/index.ts
- schematics/utils/package-config.ts
- src/ng-package.json
- src/ng-package.prod.json
…telistedNonPeerDependencies #INFR-1293
> refactor(schematics): add utils methods, refactor testing and add whitelistedNonPeerDependencies #INFR-1293

- CHANGELOG.md
- package-lock.json
- package.json
- src/package.json
- src/version.ts
> Revert "chore(release): 8.1.33"

- schematics/dependencies.ts
- schematics/ng-add/index.spec.ts
- schematics/ng-add/index.ts
- schematics/tsconfig.json
- schematics/version.ts
- src/package.json
…add deps to package.json #INFR-1327
> feat(schematics): update deps as peerDependencies, and change ng-add add deps to package.json #INFR-1327

- src/date-picker/abstract-picker.directive.ts
- src/date-picker/api/zh-cn.js
- src/date-picker/date-picker.directive.spec.ts
> feat(datepicker): add thyStopPropagation to date-picker directive (#INFR-1351)

- src/grid/api/zh-cn.js
- src/grid/examples/custom-empty/custom-empty.component.html
- src/grid/examples/custom-empty/custom-empty.component.ts
- src/grid/examples/module.ts
- src/grid/grid.component.html
- src/grid/grid.component.ts
- src/grid/test/grid.spec.ts
> feat(grid): set empty template when model=[]

- src/guider/styles/guider-tip.scss
…shadow, #INFR-1602, #INFR-1602
> fix(guider): add guider top overflow hidden, remove guider-container shadow, #INFR-1602, #INFR-1602

- src/uploader/constant.ts
- src/uploader/test/uploader.spec.ts
- src/uploader/test/util.spec.ts
- src/uploader/util.ts
> fix(uploader): fix upload in safari support xls and xlsx type, #INFR-1564

- package-lock.json
> build: revert package-lock.json #INFR-447

- src/avatar/test/avatar.spec.ts
should name span instead of img, and emit thyError
> test(avatar): should name span instead of img, and emit thyError #INFR-447

- src/divider/styles/divider.scss
- src/styles/variables.scss
divider-primary-color use gray-200
> refactor(divider): divider-primary-color use gray-200 #INFR-1637

- src/dialog/test/dialog.spec.ts
- src/dialog/test/module.ts
> test(dialog): add dialog test #INFR-1639

- src/dialog/test/dialog-layout.spec.ts
- src/dialog/test/dialog.spec.ts
move dialog-header's title traslation
> test(dialog): move dialog-header's title traslation #INFR-1639

- site/src/app/app.module.ts
- src/core/overlay/upper-overlay.service.ts
- src/popover/examples/module.ts
- src/popover/module.ts
- src/popover/popover.config.ts
- src/popover/popover.service.ts
- src/popover/test/popover.service.spec.ts
#INFR-1391 【Popover】当弹出没有遮罩层的弹框时，页面滚动时，popover 关闭
> feat(popover): support set scrollStrategy globally

- src/card/content.component.ts
BREAKING CHANGE: remove thyAlign in thy-card-content
> fix(card): remove thyAlign in thy-card-content #INFR-1869

- src/badge/badge.component.ts
BREAKING CHANGE: replace thyColor with thyBackgroundColor
> fix(badge): replace thyColor with thyBackgroundColor #INFR-1868

- src/notify/notify-option.interface.ts
- src/notify/notify.service.ts
BREAKING CHANGE: replace ThyNotifyOption with ThyNotifyOptions and replace removeItemById with removeNotifyById
> fix(notify): remove ThyNotifyOption and removeItemById #INFR-1872

- src/dialog/footer/dialog-footer.component.ts
BREAKING CHANGE:  replace thyShowBorderTop with thyDivided
> fix(dialog): replace thyShowBorderTop with thyDivided #INFR-1870

- src/select/custom-select/custom-select.component.html
- src/select/custom-select/styles/custom-select.scss
- src/tree-select/tree-select-nodes.component.html
* fix(tree-select): fix empty style for tree-select #INFR-1952
* fix(tree-select): fix empty style for tree-select #INFR-1952
* fix(tree-select): fix empty style for tree-select #INFR-1952
* fix(tree-select): add @deprecated #INFR-1952
> fix(tree-select): fix empty style for tree-select #INFR-1952 (#1252)

- src/empty/empty.component.ts
- src/empty/test/empty.spec.ts
- src/test.ts
- fix(empty): remove HostBinding and use UpdateHostClassService #INFR-1969
- fix(empty): fix test #INFR-1969
> #INFR 1969

- src/copy/module.ts
> fix(copy): update notify import to ngx-tethys/notify fix build error #INFR-2207

- src/button/styles/button-icon.scss
BREAKING CHANGE: fix btn-icon-sm from 30px  to 32px
> fix(button): setting btn-icon-sm size to 32px #INFR-2248

- package-lock.json
- package.json
- src/button/examples/basic/basic.component.html
- src/button/examples/btn-icon/btn-icon.component.html
- src/button/examples/btn-icon/btn-icon.component.ts
- src/button/examples/btn-icon/index.md
- src/button/examples/group/group.component.html
- src/button/examples/icon/icon.component.html
- src/button/examples/icon/index.md
- src/button/examples/module.ts
- src/button/examples/size/size.component.html
- src/button/styles/button-group.scss
- src/button/styles/button.scss
- src/button/styles/mixin.scss
- move thyButtonIcon examples to btn-icon folder
- add icon example for only icon button
- refactor styles for button
> fix(button): reset padding-x for only icon button in group #INFR-2657

- src/dropdown/dropdown.directive.ts
- src/dropdown/examples/module.ts
- src/dropdown/examples/options/index.md
- src/dropdown/examples/options/options.component.html
- src/dropdown/examples/options/options.component.ts
- src/dropdown/test/dropdown.spec.ts
… placement, width and height #INFR-2857
> feat(dropdown): add thyPopoverOptions parameter temporarily supports placement, width and height #INFR-2857

- src/dropdown/doc/zh-cn.md
- src/dropdown/dropdown.directive.ts
- src/dropdown/examples/options/options.component.ts
- src/dropdown/styles/dropdown.scss
- src/dropdown/test/dropdown.spec.ts
- src/popover/styles.scss
BREAKING CHANGE: delete min-width at popover-container INFR-2886
> feat(dropdown): add default width at thyPopoverOptions #INFR-2886

- src/flexible-text/flexible-text.component.ts
- src/flexible-text/test/flexible-text.spec.ts
useing resizeOberver to update tooltips status when change client width
> fix(flexibletext):tooltips status error when client resize #INFR-1575

- site/src/assets/fonts/wtd/demo.css
- src/action/styles/mixin.scss
- src/date-picker/range-picker.component.spec.ts
- src/layout/api/zh-cn.js
- src/layout/content-main.component.ts
- src/layout/content-section.component.ts
- src/layout/content.component.ts
- src/layout/examples/header/header.component.html
- src/layout/examples/header/header.component.scss
- src/layout/examples/module.ts
- src/layout/examples/subheader/subheader.component.html
- src/layout/header.component.ts
- src/layout/layout.component.ts
- src/layout/styles/layout.scss
- src/nav/doc/zh-cn.md
- src/nav/examples/responsive/responsive.component.html
- src/nav/examples/size/size.component.html
- src/nav/examples/type/type.component.html
- src/nav/nav-link.directive.ts
- src/nav/nav.component.html
- src/nav/nav.component.ts
- src/nav/styles/icon-nav.scss
- src/nav/styles/mixin.scss
- src/nav/styles/nav.scss
- src/nav/styles/theme.scss
- src/nav/test/nav.component.spec.ts
- src/styles/variables.scss
- rename thyNavLink to thyNavItem
- add xlg lg md sm sizes for thy-header
- add thyType: pulled for thy-nav
> feat: update nav and thy-header size and refactor styles

- CHANGELOG.md
- src/image/preview/image-preview.component.ts
- src/image/styles/image.scss
- src/image/test/image.preview.spec.ts
This reverts commit 5cf7939861e48874406821703d890115ada7fe4d.
> Revert "Merge branch 'v12.x' into master (#1766)"

- src/action/examples/text/text.component.html
- src/action/styles/mixin.scss
> fix(action): fix action text color not change when thyActonActive is true

- src/styles/variables.scss
> refactor(divider): the variable $divider-text-padding from 1em to 8px #INFR-3477

- src/progress/examples/basic/basic.component.html
- src/progress/examples/basic/basic.component.scss
- src/progress/examples/basic/basic.component.ts
- src/progress/examples/stacked/stacked.component.html
- src/progress/examples/stacked/stacked.component.ts
- src/progress/progress.component.ts
- src/progress/styles/progress.scss
- src/styles/variables.scss
BREAKING CHANGES
In previous versions, the primary color was #73d897 which was close to the success color, you should update thyType="primary" to thyType="success" and set thyType="success" without  thyType's thy-progress
> fix(progress): update primary color from 73d897 to $primary #INFR-3563

- src/action/action.component.html
- src/action/action.component.ts
- src/action/doc/zh-cn.md
- src/action/examples/basic/basic.component.html
- src/action/examples/group/group.component.html
- src/action/examples/hover/hover.component.html
- src/action/examples/hover/hover.component.scss
- src/action/examples/hover/hover.component.ts
- src/action/examples/hover/index.md
- src/action/examples/text/text.component.html
- src/action/examples/theme/theme.component.html
- src/action/examples/type/type.component.html
- src/action/styles/action.scss
- src/action/test/action.spec.ts
- src/dropdown/examples/basic/basic.component.html
- src/layout/examples/header/header.component.html
- src/layout/examples/sidebar/sidebar.component.html
1. add thyHoverIcon support hover switch diff icon
2. add thyIcon, thyActive instead of thyActionIcon, thyActionActive
3. add hover transition styles
> feat(action): add thyHoverIcon support hover switch diff icon and add thyIcon, thyActive instead of thyActionIcon, thyActionActive #INFR-3569

- src/styles/variables.scss
sm 的导航左右间距为 8px
md 的导航左右间距为 16px
> fix(nav): update sm nav padding-x to 8px and md padding-x to 16px

- src/transfer/transfer-list.component.html
- src/transfer/transfer-list.component.ts
> feat(transfer): lock has fixed item can not be move to unlock #INFR-3706

- src/select/examples/auto-expend/index.md
- src/select/examples/basic/index.md
- src/select/examples/custom-basic/custom-basic.component.html
- src/select/examples/custom-basic/index.md
- src/select/examples/disabled/disabled.component.html
- src/select/examples/disabled/disabled.component.ts
- src/select/examples/disabled/index.md
- src/select/examples/empty-option/index.md
- src/select/examples/footer/index.md
- src/select/examples/group/index.md
- src/select/examples/module.ts
- src/select/examples/multiple/index.md
- src/select/examples/multiple/multiple.component.html
- src/select/examples/scroll-load/index.md
- src/select/examples/search/index.md
- src/select/examples/server-search/index.md
- src/select/examples/size/index.md
- src/select/examples/top-display/index.md
- src/shared/option/styles/option.mixin.scss
- src/styles/variables.scss
1. 调整下拉选项禁用样式为 opacity: 0.5
2. 新增 disabled 示例，包含单选、多选、以及下拉选项的禁用
> refactor(select): adjust select options disabled style and add disabled example #INFR-4377

- src/nav/nav-item.directive.ts
- src/nav/styles/mixin.scss
- src/nav/styles/nav.scss
- src/nav/test/nav.component.spec.ts
- src/tabs/test/tabs.spec.ts
> feat(nav): replace nav component active-class 'active' to 'nav-active' #INFR-4482

- src/nav/nav-item.directive.ts
- src/nav/styles/mixin.scss
- src/nav/styles/nav.scss
- src/nav/test/nav.component.spec.ts
- src/tabs/test/tabs.spec.ts
> Revert "feat(nav): replace nav component active-class 'active' to 'nav-active' #INFR-4482"

- src/avatar/styles/avatar.scss
> Revert "fix(avatar): fix in styx instead"

- src/property/styles/properties.scss
- src/styles/variables.scss
BREAKING CHANGE:
- update label height 32px, remove margin-bottom for vertical
- remove label width 100px for vertical, update  display to inline-grid
> feat(property): update label height to 32px and remove column padding use gap #INFR-5258

- CHANGELOG.md
- cdk/package.json
- package-lock.json
- package.json
- schematics/version.ts
- src/package.json
- src/version.ts
> Revert "build: release 14.2.0-next.7"

- .docgenirc.js
- src/shared/base-form-check.component.ts
- src/shared/directives/thy-autofocus.directive.ts
- src/shared/directives/thy-drag-drop.directive.ts
- src/shared/directives/view-outlet.directive.spec.ts
- src/shared/directives/view-outlet.directive.ts
- src/shared/doc/zh-cn.md
- src/shared/examples/module.ts
- src/shared/examples/view-outlet/view-outlet.component.html
- src/shared/examples/view-outlet/view-outlet.component.ts
- src/shared/index.ts
- src/shared/ng-transclude.directive.ts
- src/shared/option/group/option-group.component.ts
- src/shared/option/list-option/list-option.component.ts
- src/shared/option/option-group.component.ts
- src/shared/option/option.component.ts
- src/shared/select/select-control/select-control.component.ts
- src/shared/shared.module.ts
1. 新增 thyViewOutlet 指令渲染 Component 或者 TemplateRef（包含示例和测试）
2. 放开 shared 文件夹，新增文档展示通用指令
> feat(shared): add thyViewOutlet directive render component or template and add docs for shared #INFR-5803

- src/form/examples/full/full.component.html
- src/input/input.component.html
- src/input/input.component.ts
- src/input/input.directive.ts
- src/input/test/input-component.spec.ts
- src/input/test/input-directive.spec.ts
> feat(input): remove the thyAutocomplete of thyInput & thy-input #INFR-6523 @xuhaifeng @wangkai

- src/date-picker/styles/picker.scss
> fix(date-picker): fix quick select label style justify content center #INFR-5621 @guoxin

- src/dropdown/dropdown.directive.ts
- src/dropdown/examples/module.ts
- src/dropdown/examples/options/options.component.html
- src/dropdown/examples/options/options.component.ts
- src/dropdown/test/dropdown.spec.ts
thyPlacement thyMenuInsideClosable thyPanelClass
> feat(dropdown): #INFR-3381 add common parameters @guoxin @haifeng

- src/avatar/avatar-list/avatar-list.component.html
- src/avatar/avatar-list/avatar-list.component.ts
- src/avatar/examples/list/list.component.html
- src/avatar/examples/list/list.component.ts
- src/avatar/styles/avatar-list.scss
- src/avatar/test/avatar-list.spec.ts
BREAKING CHANGE:  
- remove avatar-list thyResponsive feature. And thyMax also removed.
> refactor(avatar): remove avatar-list thyResponsive feature #INFR-7678

- schematics/ng-update/update-13/migrations/name-package-relation.ts
- scripts/name-package-relation.json
- src/date-picker/date-picker.component.spec.ts
- src/date-picker/date-picker.config.ts
- src/date-picker/date-picker.module.ts
- src/date-picker/date-picker.service.ts
- src/date-picker/doc/zh-cn.md
- src/date-picker/examples/module.ts
- src/date-picker/index.ts
- src/date-picker/lib/popups/date-popup.component.ts
- src/date-picker/range-picker.component.spec.ts
> #INFR-7677 DatePicker增加全局配置

- schematics/ng-update/core/upgrade-data.ts
> Revert "fix(schematics): add TethysVersionChanges in getTethysVersionUpgradeData"

- schematics/ng-update/core/target-version.ts
- schematics/ng-update/core/upgrade-data.ts
- schematics/ng-update/data/after-insert-element.ts
- schematics/ng-update/data/attribute-selectors.ts
- schematics/ng-update/data/before-insert-element.ts
- schematics/ng-update/data/class-names.ts
- schematics/ng-update/data/constructor-checks.ts
- schematics/ng-update/data/css-selectors.ts
- schematics/ng-update/data/element-selectors.ts
- schematics/ng-update/data/entry-points.ts
- schematics/ng-update/data/input-names-removal.ts
- schematics/ng-update/data/input-names.ts
- schematics/ng-update/data/input-values.ts
- schematics/ng-update/data/method-call-checks.ts
- schematics/ng-update/data/output-names-removal.ts
- schematics/ng-update/data/output-names.ts
- schematics/ng-update/data/property-names.ts
- schematics/ng-update/data/symbol-removal.ts
> Revert "fix(schematics): add TethysVersionChanges"

- src/date-picker/date-picker.config.ts
fix(date-picker): #INFR-8051 default shortcut ranges presets endOfWeek err
> fix(date-picker): #INFR-8051 default ranges presets endOfWeek err

- src/date-picker/lib/popups/date-popup.component.ts
- src/date-picker/range-picker.component.spec.ts
> fix(date-picker):  adjust the order for  thyShortcutValueChange and ngModelChange #INFR-9734

- CHANGELOG.md
- cdk/package.json
- package-lock.json
- package.json
- schematics/version.ts
- src/package.json
- src/version.ts
> Revert "build: release 16.2.0-next"

- src/form/styles/form-check.scss
【Checkbox、Radio】 修改可点击的区域 和 hover展示小手的区域一致
> fix(check): fix form-check style(#INFR-9102)

- src/grid/test/grid.spec.ts
> test(grid): fix ci error

- src/select/custom-select.spec.ts
- src/select/custom-select/custom-select.component.ts
> fix(select): fix pane width & position when overlay opening and width changed #INFR-11018 @luxiaobei

- src/property/property-item.component.html
- src/property/styles/properties.scss
- src/property/test/properties.component.spec.ts
> feat(property): add background & adjust html for property-item #INFR-11030 #INFR-11089

- src/property/property-item.component.html
- src/property/styles/properties.scss
- src/property/test/properties.component.spec.ts
> feat(property): add background & adjust html for property-item merge v16.1.x #INFR-11030 #INFR-11089

- src/date-picker/date-picker.component.spec.ts
- src/date-picker/lib/popups/date-popup.component.ts
> feat(date-picker): handle update selected active date when click shortcut selection #INFR-11706 @wumeimin (#INFR-11706)

- src/select/examples/group/group.component.html
- src/select/examples/group/group.component.ts
- src/shared/option/styles/select-dropdown.scss
> refactor(select): optimize the style and docs for option group INFR-11668

- src/select/examples/custom-display/custom-display.component.html
- src/select/examples/group/group.component.html
- src/select/examples/group/group.component.ts
pretty examples for option-group and custom-display
> docs(select): pretty select example for option group #INFR-12187

- src/button/styles/button.scss
> styles(button): #INFR-12587  fix btn-outline-default hover style

- src/tree/examples/expand/expand.component.html
- src/tree/examples/expand/expand.component.ts
- src/tree/examples/module.ts
- src/tree/test/tree.spec.ts
- src/tree/tree.component.ts
- src/tree/tree.service.ts
> feat(tree): thy-tree support thyExpandedKeys and thyExpandAll #INFR-12795

- src/slider/examples/basic/basic.component.ts
- src/slider/examples/configurable/configurable.component.html
- src/slider/examples/drag-end-callback/drag-end-callback.component.ts
- src/slider/examples/input-value/input-value.component.ts
- src/slider/examples/size/size.component.ts
- src/slider/examples/type/type.component.ts
- src/slider/slider.scss
1. 优化 pointer 形状：圆圈改成椭圆
2. slider 处于 active 状态时， pointer不需要变蓝
3. 禁用状态下，pointer 线条颜色由 #f5f5f5 改成 #cacaca
4. 调整一下示例间距
﻿
> feat(slider): optimize styles for slider pointer #INFR-12896

- CHANGELOG.md
- cdk/package.json
- package-lock.json
- package.json
- schematics/version.ts
- src/package.json
- src/version.ts
> Revert "build: release 18.0.0-next.1"

- package.json
- scripts/extract-css-variables.js
- src/styles/variables.scss
- src/theme/doc/zh-cn.md
- src/theme/examples/basic/basic.component.html
- src/theme/examples/basic/basic.component.scss
- src/theme/examples/basic/basic.component.ts
- src/theme/examples/color/color.component.html
- src/theme/examples/color/color.component.ts
- src/theme/examples/color/css-variables.ts
- src/theme/examples/module.ts
- src/theme/examples/switch/switch.component.html
- src/theme/examples/switch/switch.component.ts
> docs(theme): provide theme usage guide #TINFR-1064

- src/nav/styles/nav.scss
> fix(nav): the activated item requires rounded corner son the lower left and right corners #TINFR-1509

- scripts/name-package-relation.json
- site/src/app/app.module.ts
- src/date-picker/abstract-picker.component.ts
- src/date-picker/base-picker.component.html
- src/date-picker/date-picker.config.ts
- src/date-picker/date-picker.service.ts
- src/date-picker/examples/directive/directive.component.html
- src/date-picker/examples/directive/directive.component.ts
- src/date-picker/examples/module.ts
- src/date-picker/examples/separator/separator.component.html
- src/date-picker/examples/separator/separator.component.ts
- src/date-picker/picker.component.ts
- src/date-picker/picker.pipes.spec.ts
- src/date-picker/picker.pipes.ts
- src/date-picker/picker.util.ts
- src/date-picker/range-picker.component.spec.ts
- src/date-range/date-range.component.html
- src/date-range/date-range.component.spec.ts
- src/date-range/date-range.component.ts
- src/util/date/functions.ts
- src/util/date/tiny-date.ts
- TinyDate 支持设置 date-fns 默认多语言
- 支持区间分隔符传参
- 处理区间、周、季度格式根据多语言展示
- 修复测试
> feat(date-picker): support date-fns i18n and support thySeparator

- src/nav/nav.component.ts
- src/nav/styles/nav.scss
…ter responsiveness #TINFR-1984
> fix(nav): #TINFR-1984 improve button offset calculation and adjust styles for better responsive

- src/progress/progress-circle.component.html
- src/progress/progress-circle.component.ts
circle 属性的计算依赖 strokeWidth，circle 是一个 computed signal，strokeWidth 是一个 getter。
这里将 strokeWidth 也改成 computed signal。
> refactor(progress): change strokeWidth to computed signal
