atinc/ngx-tethys

src/input/test/input-directive.spec.ts
src/store/entity-store.ts
src/store/spec/entity-store.spec.ts
src/test.ts

when using EntityStore with references, we need to pass the parameter referencesidkeys, but the idKey value will be undefined, we need to set this idKey to _id all the time, unless it is passed in manually, in addition, we will throw an error when you pass an empty idKey parameter

feat(store): merge default options throw error idKey id empty #INFR-450

---

src/autocomplete/autocomplete.trigger.directive.ts

options changes may emit document click listener rightnow

fix: add delay on afterOpend

---

src/form/styles/mixin.scss

div元素的disabled属性不能用css伪类:disabled查找

fix(input):  fix input hover disabled style

---

src/styles/variables.scss

BREAKING CHANGE
If you want to use the previous button style, please set the following variables
```
$btn-border-radius: 1.25rem !default;
$btn-border-radius-lg: 1.65rem !default;
$btn-border-radius-sm: 1rem !default;
$btn-border-radius-xs: 0.75rem !default;
```

fix(button): change button default border-radius to 4px #INFR-1778

---

src/dropdown/examples/type/type.component.html
src/dropdown/styles/mixin.scss

问题原因： 业务组件库或其他使用时会用 span 包裹一层， 这样 .icon 的样式在 span 标签上， 之前只设置了& > .icon 所以图标 hover 时颜色没有更改

fix(dropdown): fix hover icon color to dropdown(#INFR-3657)

---

src/breadcrumb/examples/icon/icon.component.html
src/breadcrumb/styles/breadcrumb.scss
src/dropdown/examples/icon/icon.component.html
src/dropdown/styles/dropdown.scss
src/styles/mixins/icon-text.scss

1. DropdownMenuItem 现在的图标是不用加一个 span 套一个图标了，但是之前如果设置了 span 同时 span 上加了一个 icon class 类名，这样会导致有2个间距，为了兼容之前的样式只在 Item 直接的子中设置 icon 间距，套一个 span 不会设置间距
2. 面包屑 Item 如果是非链接的场景下，图标和文字的间距没有设置，这次补上非链接的场景

fix(dropdown): update icon spacing to child combinator and set icon-text spacing without link for breadcrumb-item

---

src/icon/doc/zh-cn.md

按当前官方文档给出的icon会出现找不到icon的错误：
产生该错误的原因是未在整个项目中注册iconResource。
补充在AppModule中注册iconResource后，icon正确显示。

补充官方文档ICON组件导入

---

src/time-picker/styles/time-picker.scss
src/time-picker/test/time-picker-panel.component.spec.ts
src/time-picker/test/time-picker.component.spec.ts
src/time-picker/time-picker-panel.component.ts
src/time-picker/time-picker.component.html
src/time-picker/time-picker.component.ts

1. 输入不合法值后还原为之前的值
2. 在不可清空状态下，手动清空输入框中的值还原为之前的值
**其他**
1. 修复在外部增加 padding 导致后置图标位置不正确
2. ngModel 支持 Date | number 类型
3. 选择此刻后关闭弹窗
5. 修复一些逻辑问题
6. 补充测试

fix(time-picker): fix use origin value when input not valid date and improve test #INFR-4316

---

src/property/styles/properties.scss

label 内容过多的时候和鼠标移动上去显示的边框加一点间距
之前的贴一起了

fix(property): update padding-right to 16px for thy-properties-item-label

---

src/button/button.component.ts
src/input/styles/input-group.scss

fix(input): add display inline-flex for input-group-prefix and replace UpdateHostClassService with useHostRenderer for button

---

src/guider/examples/custom-position/custom-position.component.html
src/guider/examples/custom-position/custom-position.component.ts
src/guider/examples/multi-step-tip/multi-step-tip.component.ts
src/guider/guider-step-ref.ts
src/guider/guider.class.ts
src/guider/test/guider.spec.ts
src/guider/utils.ts

BREAKING CHANGE:
ThyGuiderConfig.defaultPosition is {x: number, y: number} type from [number, number];
ThyGuiderStep.target now is support {x: number, y: number} and remove [number,  number] type;

refactor(guider): use {x: number, y: number} instead of [number, number] #INFR-5438

---

src/tree/examples/checkable/checkable.component.html
src/tree/examples/mocks.ts
src/tree/styles/tree.scss
src/tree/test/mock.ts
src/tree/test/tree.spec.ts
src/tree/tree-node.component.html
src/tree/tree-node.component.ts
src/tree/tree.service.ts

BREAKING CHANGES
1. cannot modify selected state if node is disabled
2. If there is an unselected disabled node in the child node,  when the parent is selected, the selected state of the parent is **indeterminate**
3. If there is a selected disabled node in the child node, when the parent node is unchecked, the state of the parent node is **indeterminate**

fix(tree): prevent modification of selected state of disabled nodes #INFR-7372

---

src/styles/modules/tables.scss
src/styles/variables.scss

fix(table): thyTheme值为bordered且可拖拽时，拖拽图标和文字之间的间距过大 #INFR-8217

---

src/table/enums/column-skeleton-type.ts
src/table/enums/index.ts
src/table/examples/pagination/pagination.component.html
src/table/examples/pagination/pagination.component.ts
src/table/examples/skeleton/skeleton.component.html
src/table/examples/skeleton/skeleton.component.ts
src/table/index.ts
src/table/styles/skeleton.scss
src/table/table-skeleton.component.html
src/table/table-skeleton.component.ts
src/table/table.component.html
src/table/table.component.ts
src/table/table.interface.ts
src/table/test/table-skeleton.spec.ts
src/table/test/table.spec.ts

1. thy-table-skeleton 支持设置 thyHeadless、thySize、thyTheme、thyMinWidth、thyColumns 参数。默认开启动画。
2. thy-table 新增参数：thyColumnSkeletonTypes，支持设置内置骨架屏的列类型，骨架列宽和column列宽一致。
3. thy-table 新增参数：thyHeadless，并兼容 thyShowHeader，标记 thyShowHeader 为废弃。
4. thy-table 内置的 thy-loading 改成 thy-table-skeleton，标记 thyLoadingText 为废弃。
5. 单元测试

feat(table): replace loading with skeleton and make skeleton stronger #INFR-9201

---

src/switch/examples/disabled/disabled.component.html
src/switch/switch.component.ts
src/switch/test/switch.component.spec.ts

<thy-switch [thyDisabled]="true"></thy-switch>
这种方式禁用有效。
<thy-switch [thyDisabled]="true" [(ngModel)]="isChecked"></thy-switch>
这种方式禁用无效。原因：ControlValueAccessor.setDisabledState 的调用覆盖了原先设置的 thyDisabled 值。
修复后以下两种方式均禁用有效：
<thy-switch [thyDisabled]="true" [(ngModel)]="isChecked"></thy-switch>
<thy-switch disabled [(ngModel)]="isChecked"></thy-switch>

fix(switch): the switch thyDisabled does not take effect when using ngModel #INFR-10583

---

src/testing/dispatcher-events.ts
src/testing/events.ts
src/tree/test/tree.spec.ts
src/tree/test/utils.ts

问题：目前master分支有 10个 拖拽相关的单元测试都报错了。
原因：MouseEvent.initMouseEvent() 方法已废弃，而且它不支持 detail、buttons 参数。 
解决：使用 new MouseEvent()  替换  MouseEvent.initMouseEvent()，并设置上detail、buttons配置。

refactor(testing): use the MouseEvent constructor to replace the deprecated initMouseEvent and set default value for detail and buttons INFR-11454

---

src/resizable/resizable.directive.ts
src/resizable/styles/resizable.scss

BREAKING CHANGE: remove set relative positon in ngAfterViewInit

fix(resize): set position by css #INFR-11934

---

src/radio/group/radio-group.component.ts

fix Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'disabled': 'false'. Current value: 'undefined'.

fix(radio): fix ExpressionChangedAfterItHasBeenCheckedError for thyDisabled  #INFR-12186

---

src/date-picker/abstract-picker.component.ts
src/date-picker/base-picker.component.html
src/date-picker/date-picker.component.spec.ts
src/date-picker/date-picker.config.ts
src/date-picker/examples/basic/basic.component.html
src/date-picker/examples/directive/directive.component.html
src/date-picker/examples/directive/directive.component.ts
src/date-picker/examples/shortcut/shortcut.component.html
src/date-picker/lib/popups/date-popup.component.ts
src/date-picker/picker.util.ts
src/date-picker/range-picker.component.spec.ts

1. 支持 `thyTimestampPrecision: 'seconds' | 'milliseconds' = 'seconds' ` 设置时间戳精度，默认 'seconds'
2. 支持全局配置 `defaultTimestampPrecision`， 默认为 'seconds'
3. 统一处理返回值的时间戳精度（ 日期、指令、快捷操作 ）

feat(date-picker): support set time tamp length default length to 10 #INFR-11707 @wumeimin @xuhaifeng (#INFR-11707)

---

src/anchor/anchor.component.ts
src/anchor/test/anchor.component.spec.ts

水平布局下，thy-anchor-link 没有嵌套时，不应该打印警告

fix(anchor): warnings should not be displayed when the thy anchor link is not nested under  horizontal layout #TINFR-480

---

src/action/action.component.ts
src/icon/icon.component.ts
src/input-number/input-number.component.ts
src/progress/progress.component.ts
src/property/property-item.component.ts
src/resizable/resizable.directive.ts
src/util/helpers/helpers.ts

1. input 中指定的 TransformT 类型应该和 transform 函数参数类型保持一致，否则之后开启严格类型模式后会有「类型不匹配」的报错。
2. 我使用的 coerceBooleanProperty 是我们自己的函数，指定了参数类型是 value: ThyBooleanInput。
而 numberAttribute 是 @angular/core 提供的，接收的类型是 unknown，我们无法指定为 value: ThyNumberInput，所以先把 ThyNumberInput 删了。

refactor: the TransormT type specified in input should be consistent with the transform function parameter type
